# Generated by Django 2.1.2 on 2018-11-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usrs', '0007_auto_20181104_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='md5s',
            field=models.CharField(default=23, max_length=500),
            preserve_default=False,
        ),
    ]
