# Generated by Django 2.1.2 on 2018-11-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usrs', '0008_book_md5s'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='md5s',
            field=models.CharField(max_length=100),
        ),
    ]
