# Generated by Django 2.1.2 on 2018-11-04 09:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usrs', '0009_auto_20181104_0747'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('name', 'ownr')},
        ),
    ]
