# Generated by Django 2.1.2 on 2018-11-20 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usrs', '0010_auto_20181104_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='md5s',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
