# Generated by Django 2.1.2 on 2018-11-20 14:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usrs', '0011_auto_20181120_0941'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('name', 'ownr', 'md5s')},
        ),
    ]
