# Generated by Django 2.1.2 on 2018-11-21 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usrs', '0012_auto_20181120_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='index',
            field=models.FileField(null=True, upload_to='usrs.BookIndex/bytes/filename/mimetype'),
        ),
    ]
