# Generated by Django 2.1.2 on 2018-11-21 11:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usrs', '0013_auto_20181121_0613'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='sharedwith',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
